FROM php:7.4-fpm

RUN apt-get update && apt-get upgrade -y
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        libssl-dev \
        libwebp-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
    && docker-php-ext-configure \
        gd --enable-gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install \
        exif \
        gd \
        zip \
        intl \
        mysqli \
        pdo pdo_mysql


RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony
COPY symfony/ /var/www/symfony
RUN chown -R 1000:1000 /var/www/symfony
RUN chmod -R 777 /var/www/symfony/var
WORKDIR /var/www/symfony