FROM php:8.0.3-fpm

RUN apt-get update && apt-get upgrade -y
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        libssl-dev \
        libwebp-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
    && docker-php-ext-configure \
        gd --enable-gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install \
        exif \
        gd \
        zip \
        intl \
        mysqli \
        pdo pdo_mysql

RUN pecl install xdebug-3.0.3 && docker-php-ext-enable xdebug
RUN mkdir -p symfony/var/oauth
RUN openssl genrsa -out symfony/var/oauth/private.key 2048
RUN openssl rsa -in symfony/var/oauth/private.key -pubout -out symfony/var/oauth/public.key

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony
COPY docker/php/xdebug.ini $PHP_INI_DIR/conf.d/xdebug.ini
COPY symfony/ /var/www/symfony
RUN chmod -R 777 /var/www/symfony/public/uploads
RUN chmod -R 777 /var/www/symfony/public/media
RUN chown -R 1000:1000 /var/www/symfony
WORKDIR /var/www/symfony