# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public/uploads'
        user_profile_picture:
            filesystem:
                data_root: '%kernel.project_dir%/public/uploads/user'
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        user_profile_picture:
            data_loader: user_profile_picture
            quality: 90
            filters:
                thumbnail: { size: [200, 200], mode: outbound }