framework:
    messenger:
      default_bus: command.bus
      buses:
        command.bus:
          middleware:
            - doctrine_transaction
            - validation
        query.bus:
          middleware:
            - doctrine_transaction
            - validation
        event.bus: ~